---
title: "Choropleth map with R"
title-prefix: "UNHCR Dataviz Platform"
author:
  - "Cedric Vidonne"
  - "Lei Chen"
output:
  html_document:
    theme: null
    self_contained: false
    highlight: "pygments"
    includes:
      in_header:
        - "../rmd_includes/r_geospatial_head.html"
        - "../rmd_includes/in_head.html"
      before_body: "../rmd_includes/header.html"
      after_body:
        - "../rmd_includes/r_geospatial.html"
        - "../rmd_includes/footer.html"
        - "../rmd_includes/footer_script.html"
params:
  tool: R
  chart_type: Choropleth map
  url_cat: geospatial
  url_chart: choropleth-map
---

```{r setup, include=FALSE}
knitr::opts_knit$set(base.dir = "../../assets/img/tools/",
                     base.url = "../../assets/img/tools/")
knitr::opts_chunk$set(echo = FALSE,
                      fig.path= paste0(tolower(params$tool),"/"),
                      message = FALSE,
                      warning = FALSE,
                      collapse = TRUE,
                      comment = "#>",
                      dev = "svglite",
                      fig.showtext = TRUE,
                      fig.retina = 2,
                      dpi = 300)
# Load packages
library(unhcrthemes)
library(tidyverse)
library(scales)
library(sf)
```

<main id="tools" class="container mt-5">

<!-- Breadcrumb is filled automatically with the text from Title and Tool parameter in YAML --> 
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="../../">Home</a></li>
        <li class="breadcrumb-item"><a href="../">Tools</a></li>
        <li class="breadcrumb-item"><a href="../`r tolower(params$tool)`/">`r params$tool`</a></li>
        <li class="breadcrumb-item active" aria-current="page">`r rmarkdown::metadata$title`</li>
    </ol>
</nav>


<!-- Intro header --> 
<div class="my-5 text-center">

## `r rmarkdown::metadata$title`

<div class="row justify-content-center">
<div class="col-lg-8">

<!-- Only text to change below, the rest comes from the YAML --> 
A choropleth map is a type of thematic map in which areas are shaded or patterned according to a data variable. The variable is categorized into intervals, with each interval represented by a colour, and the map filled accordingly.

More about: <a href="../../chart_gallery/`r params$url_cat`.html#`r params$url_chart`">`r params$chart_type`</a>

</div>
</div>
</div>


----

<!-- Beginning of section, should be preceded by hr (----) --> 
<section class="my-5">

### Choropleth map

<div class="row">

<!-- First column for large screen --> 
<div class="col-lg-6">

```{r choropleth_map, echo=TRUE, fig.show = 'hide', warning=FALSE, message=FALSE}
# Loading required packages
library(unhcrthemes)
library(tidyverse)
library(scales)
library(sf)

# Load data
df <- read_csv("https://raw.githubusercontent.com/GDS-ODSSS/unhcr-dataviz-platform/master/data/geospatial/choropleth_map.csv")
poly_url <- "https://raw.githubusercontent.com/GDS-ODSSS/unhcr-dataviz-platform/master/data/geospatial/world_polygons_simplified.json"
line_url <- "https://raw.githubusercontent.com/GDS-ODSSS/unhcr-dataviz-platform/master/data/geospatial/world_lines_simplified.json"

# Add CRS to poly and join values from csv
poly <- read_sf(poly_url) |> 
  st_set_crs(4326) |> 
  left_join(df, by = c("color_code" = "iso3")) |> 
  mutate(legend = case_when(
    refugees < 1e4 ~ "<10k",
    refugees < 1e5 ~ "10k-100k",
    refugees < 1e6 ~ "100k-1M",
    is.na(refugees) ~ NA_character_,
    TRUE ~ ">1M"
  )) |> 
  mutate(legend = as_factor(legend) |> 
           fct_relevel("<10k", "10k-100k", "100k-1M", ">1M"))
  

# Sort line type
line <- read_sf(line_url) |>
  mutate(
    type = as_factor(type) |>
      fct_relevel("solid", "dashed", "dotted", "dashed-dot")
  ) |> 
  st_set_crs(4326)


# Plot
ggplot() +
  geom_sf(data = poly,
          aes(fill = legend),
          color = "transparent") +
  geom_sf(data = line,
          aes(linetype = type),
          color = "white",
          linewidth = .25,
          show.legend = FALSE) +
  coord_sf(crs = st_crs('ESRI:54030'),
           expand = FALSE) +
  scale_linetype_manual(values = c(1, 2, 3, 4)) +
  scale_fill_unhcr_d(palette = "pal_blue") +
  labs(
    title = "Global refugee displacement by country of asylum | 2021",
    caption = "The boundaries and names shown and the designations used on this map do not imply official\nendorsement or acceptance by the United Nations.\nSource: UNHCR Refugee Data Finder\n© UNHCR, The UN Refugee Agency"
  ) +
  theme_unhcr_map(rel_small = .75,
                  rel_tiny = .65)
```

</div>
<!-- End First column --->

<!-- Second column for large screen --> 
<div class="col-lg-6">


```{r choropleth_map_plot, ref.label= 'choropleth_map', echo=FALSE, error=FALSE, results='hide', out.width="100%", fig.height=5}

```

</div>
<!-- End Second column --->

</div>
</section>
<!-- End of section --->


<!-- To add sections just copy the whole code between the above section tag --->

</main>
