---
title: "Stacked column chart with R"
title-prefix: "UNHCR Dataviz Platform"
author:
  - "Cedric Vidonne"
  - "Lei Chen"
output:
  html_document:
    theme: null
    self_contained: false
    highlight: "pygments"
    includes:
      in_header:
        - "../rmd_includes/r_comparison_head.html"
        - "../rmd_includes/in_head.html"
      before_body: "../rmd_includes/header.html"
      after_body:
        - "../rmd_includes/r_comparison.html"
        - "../rmd_includes/footer.html"
        - "../rmd_includes/footer_script.html"
params:
  tool: R
  chart_type: Stacked column chart
  url_cat: comparison
  url_chart: column-stacked
---

```{r setup, include=FALSE}
knitr::opts_knit$set(base.dir = "../../assets/img/tools/",
                     base.url = "../../assets/img/tools/")
knitr::opts_chunk$set(echo = FALSE,
                      fig.path= paste0(tolower(params$tool),"/"),
                      message = FALSE,
                      warning = FALSE,
                      collapse = TRUE,
                      comment = "#>",
                      dev = "svglite",
                      fig.showtext = TRUE,
                      fig.retina = 2,
                      dpi = 300)
library(unhcrthemes)
library(tidyverse)
library(scales)
```

<main id="tools" class="container mt-5">

<!-- Breadcrumb is filled automatically with the text from Title and Tool parameter in YAML --> 
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="../../">Home</a></li>
        <li class="breadcrumb-item"><a href="../">Tools</a></li>
        <li class="breadcrumb-item"><a href="../`r tolower(params$tool)`/">`r params$tool`</a></li>
        <li class="breadcrumb-item active" aria-current="page">`r rmarkdown::metadata$title`</li>
    </ol>
</nav>

<!-- Intro header --> 
<div class="my-5 text-center">

## `r rmarkdown::metadata$title`

<div class="row justify-content-center">
<div class="col-lg-8">

<!-- Only text to change below, the rest comes from the YAML --> 
The stacked column chart stacks vertical bars that represent different groups on top of each other. The height of the stacked bar shows the combined value of the groups.

More about: <a href="../../chart_gallery/`r params$url_cat`.html#`r params$url_chart`">`r params$chart_type`</a>

</div>
</div>
</div>


----

<!-- Beginning of section, should be preceded by hr (----) --> 
<section class="my-5">

### Stacked column chart

<div class="row">

<!-- First column for large screen --> 
<div class="col-lg-6">

```{r column_stacked_code, echo=TRUE, eval=FALSE}
# Loading required packages
library(unhcrthemes)
library(tidyverse)
library(scales)

# Loading data
df <- read_csv("https://raw.githubusercontent.com/GDS-ODSSS/unhcr-dataviz-platform/master/data/comparison/column_stacked.csv")

# Plot
ggplot(df) +
  geom_col(aes(x = year,
               y = rst_in_thousand,
               fill = rst_type),
           width = 0.7) +
  scale_fill_unhcr_d(palette = "pal_unhcr",
                     nmax = 2,
                     order = 2:1) +
  scale_x_continuous(breaks = pretty_breaks(n = 11)) +
  scale_y_continuous(expand = expansion(c(0, 0.2))) +
  labs(title = "Resettlement by UNHCR and others | 2010-2020",
       y = "Number of people (thousand)",
       caption = "Source: data source here\n© UNHCR, The UN Refugee Agency") +
  theme_unhcr(grid = "Y",
              axis = "x",
              axis_title = "y")
```

</div>
<!-- End First column --->

<!-- Second column for large screen --> 
<div class="col-lg-6">


```{r r_column_stacked_chart, echo=FALSE, out.width="100%", fig.height=5.7, fig.alt="A stacked column chart showing resettlement by UNHCR and others | 2010-2020"}
# Loading data
df <- read_csv("https://raw.githubusercontent.com/GDS-ODSSS/unhcr-dataviz-platform/master/data/comparison/column_stacked.csv")

ggplot(df) +
  geom_col(aes(x = year, y = rst_in_thousand, fill = rst_type),
           width = 0.7) +
  scale_fill_unhcr_d(palette = "pal_unhcr", nmax = 2,
                     order = 2:1) +
  scale_x_continuous(breaks = pretty_breaks(n = 11)) +
  scale_y_continuous(expand = expansion(c(0, 0.2))) +
  labs(title = "Resettlement by UNHCR and others | 2010-2020",
       y = "Number of people (thousand)",
       caption = "Source: data source here\n© UNHCR, The UN Refugee Agency") +
  theme_unhcr(font_size = 13, grid = "Y", axis = "x", axis_title = "y")
```

</div>
<!-- End Second column --->

</div>
</section>
<!-- End of section --->

----

<!-- Beginning of section, should be preceded by hr (----) --> 
<section class="my-5">

### Stacked column chart with labels

<div class="row">

<!-- First column for large screen --> 
<div class="col-lg-6">

```{r column_stacked_label_code, echo=TRUE, eval=FALSE}
# Loading required packages
library(unhcrthemes)
library(tidyverse)
library(scales)

# Loading data
df <- read_csv("https://raw.githubusercontent.com/GDS-ODSSS/unhcr-dataviz-platform/master/data/comparison/column_stacked.csv")

# Plot
ggplot(df) +
  geom_col(aes(x = year,
               y = rst_in_thousand,
               fill = rst_type),
           width = 0.7) +
  geom_text(aes(x = year,
                y = rst_in_thousand,
                color = rst_type,
                label = rst_in_thousand),
            position = position_stack(vjust = 0.5),
            show.legend = FALSE,
            size = 8/.pt) +
  scale_color_manual(values = c("#000000", "#FFFFFF")) +
  scale_fill_unhcr_d(palette = "pal_unhcr",
                     nmax = 2,
                     order = 2:1) +
  scale_x_continuous(breaks = pretty_breaks(n = 11)) +
  scale_y_continuous(expand = expansion(c(0, 0.1))) +
  labs(title = "Resettlement by UNHCR and others | 2010-2020",
       subtitle = "Number of people (thousand)",
       caption = "Source: data source here\n© UNHCR, The UN Refugee Agency") +
  theme_unhcr(grid = FALSE,
              axis = "x",
              axis_title = FALSE,
              axis_text = "x")
```

</div>
<!-- End First column --->

<!-- Second column for large screen --> 
<div class="col-lg-6">


```{r r_column_stacked_label_chart, echo=FALSE, out.width="100%", fig.height=5.7, fig.alt="A stacked column chart showing resettlement by UNHCR and others | 2010-2020"}
# Loading data
df <- read_csv("https://raw.githubusercontent.com/GDS-ODSSS/unhcr-dataviz-platform/master/data/comparison/column_stacked.csv")

ggplot(df) +
  geom_col(aes(x = year, y = rst_in_thousand, fill = rst_type),
           width = 0.7) +
  geom_text(aes(x = year, y = rst_in_thousand, color = rst_type, label = rst_in_thousand),
            position = position_stack(vjust = 0.5),
            show.legend = FALSE,
            size = 11.5/.pt) +
  scale_color_manual(values = c("#000000", "#FFFFFF")) +
  scale_fill_unhcr_d(palette = "pal_unhcr", nmax = 2, order = 2:1) +
  scale_x_continuous(breaks = pretty_breaks(n = 11)) +
  scale_y_continuous(expand = expansion(c(0, 0.1))) +
  labs(title = "Resettlement by UNHCR and others | 2010-2020",
       subtitle = "Number of people (thousand)",
       caption = "Source: data source here\n© UNHCR, The UN Refugee Agency") +
  theme_unhcr(font_size = 13, grid = FALSE, axis = "x", axis_title = FALSE, axis_text = "x")
```

</div>
<!-- End Second column --->

</div>
</section>
<!-- End of section --->

<!-- To add sections just copy the whole code between the above section tag --->

</main>
