---
title: "Slope chart with R"
title-prefix: "UNHCR Dataviz Platform"
author:
  - "Cedric Vidonne"
  - "Lei Chen"
output:
  html_document:
    theme: null
    self_contained: false
    highlight: "pygments"
    includes:
      in_header:
        - "../rmd_includes/r_change_over_time_head.html"
        - "../rmd_includes/in_head.html"
      before_body: "../rmd_includes/header.html"
      after_body:
        - "../rmd_includes/r_change_over_time.html"
        - "../rmd_includes/footer.html"
        - "../rmd_includes/footer_script.html"
params:
  tool: R
  chart_type: Slope chart
  url_cat: change_over_time
  url_chart: slope
---

```{r setup, include=FALSE}
knitr::opts_knit$set(base.dir = "../../assets/img/tools/",
                     base.url = "../../assets/img/tools/")
knitr::opts_chunk$set(echo = FALSE,
                      fig.path= paste0(tolower(params$tool),"/"),
                      message = FALSE,
                      warning = FALSE,
                      collapse = TRUE,
                      comment = "#>",
                      dev = "svglite",
                      fig.showtext = TRUE,
                      fig.retina = 2,
                      dpi = 300)
library(unhcrthemes)
library(tidyverse)
library(scales)
library(ggrepel)
```

<main id="tools" class="container mt-5">

<!-- Breadcrumb is filled automatically with the text from Title and Tool parameter in YAML --> 
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="../../">Home</a></li>
        <li class="breadcrumb-item"><a href="../">Tools</a></li>
        <li class="breadcrumb-item"><a href="../`r tolower(params$tool)`/">`r params$tool`</a></li>
        <li class="breadcrumb-item active" aria-current="page">`r rmarkdown::metadata$title`</li>
    </ol>
</nav>

<!-- Intro header --> 
<div class="my-5 text-center">

## `r rmarkdown::metadata$title`

<div class="row justify-content-center">
<div class="col-lg-8">

<!-- Only text to change below, the rest comes from the YAML --> 
A slope chart looks like a line chart, but unlike the line chart, it has only two data points for each line. The change between two data points can be easily identified with connected lines (slope up means increase, slope down means decrease).

More about: <a href="../../chart_gallery/`r params$url_cat`.html#`r params$url_chart`">`r params$chart_type`</a>

</div>
</div>
</div>


----

<!-- Beginning of section, should be preceded by hr (----) --> 
<section class="my-5">

### Slope chart

<div class="row">

<!-- First column for large screen --> 
<div class="col-lg-6">

```{r slope_code, echo=TRUE, eval=FALSE}
# Loading required packages
library(unhcrthemes)
library(tidyverse)
library(ggrepel)

# Loading data
df <- read_csv("https://raw.githubusercontent.com/GDS-ODSSS/unhcr-dataviz-platform/master/data/change_over_time/slope.csv")

# Plot
ggplot(df, aes(x = year, y = refugee_number, group = country_origin)) +
  geom_line(size = 0.75, color = unhcr_pal(n = 1, "pal_blue")) +
  geom_text_repel(data = df |> filter(year == 2016),
            aes(label = paste(country_origin, if_else(refugee_number > 1e6, paste0(round(refugee_number/1e6, 1),"M"), paste0(round(refugee_number/1e3, 1),"k")))),
            size = 8/.pt, hjust = 1, direction = "y", nudge_x = -0.3) +
  geom_text_repel(data = df |> filter(year == 2021),
            aes(label = paste(country_origin, if_else(refugee_number > 1e6, paste0(round(refugee_number/1e6, 1),"M"), paste0(round(refugee_number/1e3, 1),"k")))),
            size = 8/.pt, hjust = 0, direction = "y", nudge_x = 0.3) +
  geom_point(size = 2.5, color = unhcr_pal(n = 1, "pal_blue")) +
  labs(title = "Evolution of refugee population in East and\nHorn of Africa region | 2016 vs 2021",
       caption = "Source: UNHCR Refugee Data Finder\n© UNHCR, The UN Refugee Agency") +
  scale_x_continuous(breaks = c(2016, 2021),
                     limits = c(2013, 2024)) +
  scale_y_continuous(limits = c(-2e5, NA)) +
  theme_unhcr(grid = "X", axis = FALSE, axis_title = FALSE, axis_text = "X")
```

</div>
<!-- End First column --->

<!-- Second column for large screen --> 
<div class="col-lg-6">


```{r r_slope_chart, echo=FALSE, out.width="100%", fig.height=7.5}
# Loading data
df <- read_csv("https://raw.githubusercontent.com/GDS-ODSSS/unhcr-dataviz-platform/master/data/change_over_time/slope.csv")

ggplot(df, aes(x = year, y = refugee_number, group = country_origin)) +
  geom_line(size = 0.75, color = unhcr_pal(n = 1, "pal_blue")) +
  geom_text_repel(data = df |> filter(year == 2016),
            aes(label = paste(country_origin, if_else(refugee_number > 1e6, paste0(round(refugee_number/1e6, 1),"M"), paste0(round(refugee_number/1e3, 1),"k")))),
            size = 11.5/.pt, hjust = 1, direction = "y", nudge_x = -0.3) +
  geom_text_repel(data = df |> filter(year == 2021),
            aes(label = paste(country_origin, if_else(refugee_number > 1e6, paste0(round(refugee_number/1e6, 1),"M"), paste0(round(refugee_number/1e3, 1),"k")))),
            size = 11.5/.pt, hjust = 0, direction = "y", nudge_x = 0.3) +
  geom_point(size = 2.5, color = unhcr_pal(n = 1, "pal_blue")) +
  labs(title = "Evolution of refugee population in East and\nHorn of Africa region | 2016 vs 2021",
       caption = "Source: UNHCR Refugee Data Finder\n© UNHCR, The UN Refugee Agency") +
  scale_x_continuous(breaks = c(2016, 2021),
                     limits = c(2013, 2024)) +
  scale_y_continuous(limits = c(-2e5, NA)) +
  theme_unhcr(font_size = 13, grid = "X", axis = FALSE, axis_title = FALSE, axis_text = "X")
```

</div>
<!-- End Second column --->

</div>
</section>
<!-- End of section --->


<!-- To add sections just copy the whole code between the above section tag --->

</main>
