name: Docker publish

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image 
      run: docker build -f ./Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/dataviz:latest ./
    
    - name: Publish Docker image 
      run: docker push ${{ secrets.DOCKER_USERNAME }}/dataviz:latest
